#!/usr/bin/env bash
# Initialize a counter variable
counter=0

# Use a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
  if [ $counter -eq 8 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi

  ((counter++))  # Increment the counter
done
