#!/usr/bin/env bash
# Initialize a counter variable
counter=1
# Use a while loop to loop from 1 to 20
while [ $counter -le 20 ]; do
  case $counter in
    4)
      echo -e "$counter\nbad luck from China"
      ;;
    9)
      echo -e "$counter\nbad luck from Japan"
      ;;
    17)
      echo -e "$counter\nbad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac

  ((counter++))  # Increment the counter
done
