#!/usr/bin/env bash
# Function to write "I am alive!" to the file /tmp/my_process
write_alive_message() {
    while true; do
        echo "I am alive!" >> /tmp/my_process
        sleep 2
    done
}

# Write PID to /var/run/my_process.pid
echo $$ > /var/run/my_process.pid

# Start writing the "I am alive!" messages
write_alive_message
